@echo off
echo ... this script ¹2 is written by fans to optimize .png mod files in great game FACTORIO!
set path=%~d0%~p0

:start
echo ...
echo ...
echo === Launching paletted quantization with PNGQUANT...
echo ... please wait...

"%path%pngquant.exe" -ext .png -force --verbose 256 --speed=1 %1

echo ...
echo === pngquant is done! ===
echo ...
echo === Launching S4 (best) optimization with PINGO... please wait...
echo pingo is working ...

"%path%pingo.exe" -s4 %1
echo ...
echo === PINGO is done! ===

shift
if NOT x%1==x goto start